<?php

/**************************************************************************
 * PokePokemonTypeBase.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * PokePokemon Type
 *
 * This class was generated by the Harmony / Don't modify this class it will be regenerated by Harmony !
 */
class PokePokemonTypeBase extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pokeNpcpokemonsInternal', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeNpc',
                'property' => 'id',
                'required' => false))
            ->add('pokeNpcteamInternal', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeNpc',
                'property' => 'id',
                'required' => false))
            ->add('surnom')
            ->add('niveau')
            ->add('capture', 'datetime', array(
                'input'  => 'datetime',
                'required' => false,
                'widget' => 'single_text'
            ))
            ->add('type', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeTypePokemon',
                'property' => 'id',
                'required' => false))
            ->add('attaque1', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeAttaque',
                'property' => 'id',
                'required' => false))
            ->add('attaque2', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeAttaque',
                'property' => 'id',
                'required' => false))
            ->add('attaque3', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeAttaque',
                'property' => 'id',
                'required' => false))
            ->add('attaque4', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeAttaque',
                'property' => 'id',
                'required' => false))
            
            
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Pokebattle\ApiBundle\Entity\PokePokemon',
            'csrf_protection' => false
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return '';
    }
}
