<?php

/**************************************************************************
 * PokeTypeType.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Form;

use Pokebattle\ApiBundle\Form\PokeTypeTypeBase;


/**
 * PokeType Type
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokeTypeType extends PokeTypeTypeBase
{

}
