<?php

/**************************************************************************
 * PokeTypePokemonTypeBase.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * PokeTypePokemon Type
 *
 * This class was generated by the Harmony / Don't modify this class it will be regenerated by Harmony !
 */
class PokeTypePokemonTypeBase extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('attaque')
            ->add('attaque_spe')
            ->add('defence')
            ->add('defence_spe')
            ->add('vitesse')
            ->add('pv')
            ->add('pokedex')
            ->add('evolue', 'entity', array(
                'class' => 'PokebattleApiBundle:PokeTypePokemon',
                'property' => 'id',
                'required' => false))
            
            
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Pokebattle\ApiBundle\Entity\PokeTypePokemon',
            'csrf_protection' => false
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return '';
    }
}
