pokebattle_api:
    resource: "@PokebattleApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# API Auto-doc
nelmio_api_doc_index:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

pokebattle_rest_default:
    type:     rest
    resource: Pokebattle\ApiBundle\Controller\RestDefaultController
pokebattle_rest_default:
    type:     rest
    resource: Pokebattle\ApiBundle\Controller\RestDefaultController

