<?php

/**************************************************************************
 * RestDefaultController.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Controller;

/**
 * RestDefaultController
 *
 * This class was generated by Harmony. Add your own custom
 * controller methods below.
 */
class RestDefaultController extends RestDefaultControllerBase
{

}

?>
