<?php

namespace Pokebattle\ApiBundle\Controller;

use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Request\ParamFetcherInterface;

use Nelmio\ApiDocBundle\Annotation\ApiDoc;

use Symfony\Component\HttpFoundation\Request;

use Pokebattle\ApiBundle\Form\PokePokemonType;
use Pokebattle\ApiBundle\Entity\PokePokemon;
use Pokebattle\ApiBundle\Controller\RestPokeNpcController;
use Pokebattle\ApiBundle\Controller\RestPokeTypePokemonController;
use Pokebattle\ApiBundle\Controller\RestPokeAttaqueController;
use Pokebattle\ApiBundle\Controller\RestSyncController as Controller;

/**
 * PokePokemon Repository
 *
 * This class was generated by the Harmony / Doctrine ORM.
 *
 * This class will be regenerated by Harmony. DO NOT MODIFIY THIS CLASS.
 */
class RestPokePokemonControllerBase extends Controller {

    public function getNewEntity() {
        return new PokePokemon();
    }

    /**=========================================================================
     * CRUD REST
     *========================================================================*/

    /**
     * GET /{id}
     *
     * @param string pokePokemonId
     * @return Response
     * @Rest\Get("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD PokePokemon",
     *   description="Show entity"
     * )
     * @return type
     */
    public function getPokePokemonAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $data = $entityManager->getRepository('PokebattleApiBundle:PokePokemon')->findOneById($id);
        $view = $this->view($data, 200);
        return $this->handleView($view);
    }

    /**
     * POST
     *
     * @Rest\Post("")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD PokePokemon",
     *   description="Create entity",
     *   requirements={
     *      {
     *          "name"="pokeNpcpokemonsInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The pokeNpcpokemonsInternal pokePokemon",
     *      },
     *      {
     *          "name"="pokeNpcteamInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The pokeNpcteamInternal pokePokemon",
     *      },
     *      {
     *          "name"="surnom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The surnom pokePokemon",
     *      },
     *      {
     *          "name"="niveau",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The niveau pokePokemon",
     *      },
     *      {
     *          "name"="capture",
     *          "dataType"="datetime",
     *          "requirement"="",
     *          "description"="The capture pokePokemon",
     *      },
     *      {
     *          "name"="type",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The type pokePokemon",
     *      },
     *      {
     *          "name"="attaque1",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque1 pokePokemon",
     *      },
     *      {
     *          "name"="attaque2",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque2 pokePokemon",
     *      },
     *      {
     *          "name"="attaque3",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque3 pokePokemon",
     *      },
     *      {
     *          "name"="attaque4",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque4 pokePokemon",
     *      },
     *   }
     * )
     * @return type
     */
    public function createPokePokemonAction(Request $request) {
        $entity = new PokePokemon();

        $form = $this->createForm(new PokePokemonType(), $entity, array(
            'allow_extra_fields' => true
        ));
        $form->submit($request);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid" . $form->getErrors()), 400);
        }

        return $this->handleView($view);
    }

    /**
     * GET
     *
     * @Rest\Get("")
     * @Rest\QueryParam(name="page", nullable=true, requirements="\d+", default="0", description="Number of the page")
     * @Rest\QueryParam(name="quantity", nullable=true, requirements="\d+", default="0", description="Quantity of entities per page")
     * @param ParamFetcher $paramFetcher
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD PokePokemon",
     *   description="Show all entities",
     *   requirements={
     *   }
     * )
     * @return type
     */
    public function getAllPokePokemonAction(ParamFetcherInterface $paramFetcher)
    {
        $repository = $this->getDoctrine()->getRepository('PokebattleApiBundle:PokePokemon');

        $page = $paramFetcher->get('page');
        $quantity = $paramFetcher->get('quantity');

        $data = $repository->getList($page, $quantity);

        if ($data) {
            $view = $this->view(array("PokePokemons" => $data), 200);
        } else {
            $view = $this->view(null, 204);
        }

        return $this->handleView($view);
    }

    /**
     * PUT /{id}
     *
     * @Rest\Put("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD PokePokemon",
     *   description="Update entity",
     *   requirements={
     *      {
     *          "name"="pokeNpcpokemonsInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The pokeNpcpokemonsInternal pokePokemon",
     *      },
     *      {
     *          "name"="pokeNpcteamInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The pokeNpcteamInternal pokePokemon",
     *      },
     *      {
     *          "name"="surnom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The surnom pokePokemon",
     *      },
     *      {
     *          "name"="niveau",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The niveau pokePokemon",
     *      },
     *      {
     *          "name"="capture",
     *          "dataType"="datetime",
     *          "requirement"="",
     *          "description"="The capture pokePokemon",
     *      },
     *      {
     *          "name"="type",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The type pokePokemon",
     *      },
     *      {
     *          "name"="attaque1",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque1 pokePokemon",
     *      },
     *      {
     *          "name"="attaque2",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque2 pokePokemon",
     *      },
     *      {
     *          "name"="attaque3",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque3 pokePokemon",
     *      },
     *      {
     *          "name"="attaque4",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque4 pokePokemon",
     *      },
     *   }
     * )
     * @return type
     */
    public function updatePokePokemonAction($id, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokebattleApiBundle:PokePokemon')
            ->findOneById($id);

        $form = $this->createForm(new PokePokemonType(), $entity, array(
            'allow_extra_fields' => true
        ));

        $form->submit($request, false);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid"), 400);
        }

        return $this->handleView($view);
    }

    /**
     * DELETE /{id}
     *
     * @Rest\Delete("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD PokePokemon",
     *   description="Delete entity",
     * )
     * @return type
     */
    public function deletePokePokemonAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokebattleApiBundle:PokePokemon')
            ->find(array("id" => $id));

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find PokePokemon entity');
        }

        $entityManager->remove($entity);
        $entityManager->flush();

        $view = $this->view($entity, 200);
        return $this->handleView($view);
    }


}

?>