parameters:
#    pokebattle_api.example.class: Pokebattle\ApiBundle\Example

services:
#    pokebattle_api.example:
#        class: %pokebattle_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
