<?php

/**************************************************************************
 * PokeDresseurRepository.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Repository;

use Pokebattle\ApiBundle\Repository\PokeDresseurRepositoryBase;

/**
 * PokeDresseur Repository
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokeDresseurRepository extends PokeDresseurRepositoryBase {

}

?>
