<?php

/**************************************************************************
 * PokeAreneRepository.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Repository;

use Pokebattle\ApiBundle\Repository\PokeAreneRepositoryBase;

/**
 * PokeArene Repository
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokeAreneRepository extends PokeAreneRepositoryBase {

}

?>
