<?php

/**************************************************************************
 * PokePositionRepository.php, pokebattle Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 25, 2016
 *
 **************************************************************************/

namespace Pokebattle\ApiBundle\Repository;

use Pokebattle\ApiBundle\Repository\PokePositionRepositoryBase;

/**
 * PokePosition Repository
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokePositionRepository extends PokePositionRepositoryBase {

}

?>
